
/**
 * This main class simply constructs a new GUI object to run the constructor. The exception block handles input/output errors generated by retrieving text from the source website.
 * @author Jordan Roig
 * @since 15.02+7
 */
public class Module2 {

	/**
	 * This invokes the GUI constructor, which calls the other methods within and handles the rest of the program.
	 * @param args Handles text passed to the JVM via the console. Does nothing in this program but is a required part of handling the main method call.
	 * @throws Exception Allows the JVM to throw the IOException error to the catch block in the GUI class, which prints out the standard error code.
	 */
	public static void main(String[] args) throws Exception {
		//run main program
		GUI runner = new GUI();
	}
	
	
	

}
